name: docs links on snapcraft.io/docs

on: pull_request

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/snapcraft.io'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: linkchecker --no-follow-url '!https:\/\/snapcraft.io\/docs\/' --ignore-url "https://munchkin.marketo.net" --ignore-url "https://www.gstatic.com" --ignore-url "https://assets.ubuntu.com$" --ignore-url https://snapcraft.io/static/css/styles.css* --check-extern --no-warnings https://snapcraft.io/docs

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=test-bot-channel
